services:
  spring:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tripus
      SPRING_DATA_REDIS_HOST: redis
    depends_on:
      - mysql

  mysql:
    image: mysql:8.4.5
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tripus
      TZ: Asia/Seoul
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:8.0.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local