services:
#  springboot:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: springboot
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mysql

  mysql:
    image: mysql:8.4.5
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tripus
      TZ: Asia/Seoul
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql-data:
    driver: local