global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring'
    metrics_path: '/actuator/prometheus'
    static_configs:
      #      - targets: [ 'spring:8080' ]
      - targets: [ 'host.docker.internal:8080' ]