server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: debug-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: debug-logs
          __path__: /app/logs/debug.log

  - job_name: info-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: info-logs
          __path__: /app/logs/info.log

  - job_name: warn-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: warn-logs
          __path__: /app/logs/warn.log

  - job_name: error-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: error-logs
          __path__: /app/logs/error.log