server:
  port: 8080

logging:
  level:
    data: DEBUG

spring:
  application:
    name: TripUs
  devtools:
    livereload:
      enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tripus
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        auto_quote_keyword: true

mybatis:
  type-aliases-package: org.project.tripus.mapper, org.project.tripus.dto
  mapper-locations:
  - /mapper/**/*.xml

# spring security
jwt:
  expiration_time: 86400000
  secret_key: wXVmY9q+3FgDjsKqP7C8F8zJ5bQx9sd9vpl9xAyj/B0=